//limit of Combos
export const GET_LIMIT_OF_COMBOS = 'GET_LIMIT_OF_COMBOS';
export const GET_LIMIT_OF_COMBOS_SUCCESS = 'GET_LIMIT_OF_COMBOS_SUCCESS';
export const GET_LIMIT_OF_COMBOS_ERROR = 'GET_LIMIT_OF_COMBOS_ERROR';
export const ADD_LIMIT_OF_COMBO = 'ADD_LIMIT_OF_COMBO';
export const ADD_LIMIT_OF_COMBO_SUCCESS = 'ADD_LIMIT_OF_COMBO_SUCCESS';
export const ADD_LIMIT_OF_COMBO_ERROR = 'ADD_LIMIT_OF_COMBO_ERROR';

//combo data
export const CREATE_DATA_COMBO = 'CREATE_DATA_COMBO';
export const CLEAR_DATA_COMBO = 'CLEAR_DATA_COMBO';